attestation: implement android-key
pomerium/webauthn pull request #9
Opened 2021-10-04 18:58 UTC by calebdoxsey

Add android-key attestation verification as defined in the spec: https://www.w3.org/TR/webauthn-2/#sctn-android-key-attestation

I also added an `android` sub-package since part of verification is based on data supplied by android, as specified in the documentation: https://developer.android.com/training/articles/security-key-attestation#certificate_schema

Finally I added support for marshaling some structures to generate failing certificates we can use to check different errors.

Fixes https://github.com/pomerium/internal/issues/587

2021-10-04 20:52 UTC, wasaga approved these changes

2021-10-04 22:21 UTC, desimone commented on android/key.go
> +	AttestationIDImei           []byte              `asn1:"tag:714,explicit,optional"`
Flagging, but not sure how best to handle "IMEI" and "MEID" which are typically capitalized (similar to ID).

Though, in this particular case `AttestationIDImei` is much more readable than `AttestationIDIMEI`🤷‍♂️

2021-10-04 23:06 UTC, desimone requested changes
LGTM, a few suggestions for testing of the exported Marshal functions.

2021-10-05 16:26 UTC, desimone approved these changes

2021-10-05 16:30 UTC, merged